clearvars; close all;

load('SPM_N2_noRaman.mat');
nonlinear_phase_noRaman = nonlinear_phase;
load('SPM_N2.mat');
figure;
h = plot(tfwhm_all,[nonlinear_phase',nonlinear_phase_noRaman'],'linewidth',2);
set(h(1),'Color','b'); set(h(2),'Color','r');
xlabel('Pulse duration (ps)');
ylabel('Nonlinear phase (rad)');
set(gca,'fontsize',25);
l = legend('with SRS','without SRS'); legend('boxoff');
pos = get(l,'Position');
set(l,'Position',[pos(1:3),pos(4)*0.2]);
ylim([0,13]);
print(gcf,'SPM_transition_N2.pdf','-dpdf');

load('SPM_H2_noRaman.mat');
nonlinear_phase_noRaman = nonlinear_phase;
load('SPM_H2.mat');
figure;
h = plot(tfwhm_all,[nonlinear_phase',nonlinear_phase_noRaman'],'linewidth',2);
set(h(1),'Color','b'); set(h(2),'Color','r');
xlabel('Pulse duration (ps)');
ylabel('Nonlinear phase (rad)');
set(gca,'fontsize',25);
l = legend('with SRS','without SRS'); legend('boxoff');
pos = get(l,'Position');
set(l,'Position',[pos(1:3),pos(4)*0.2]);
ylim([0,13]);
print(gcf,'SPM_transition_H2.pdf','-dpdf');

figure;
h = plot(tfwhm_all,[nonlinear_phase',nonlinear_phase_noRaman'],'linewidth',10);
set(h(1),'Color','b'); set(h(2),'Color','r');
xlim([0.02,0.1]);
ylim([1,4]);
set(gca,'fontsize',60,'Color','None');
xlabel('');
ylabel('');
print(gcf,'SPM_transition_H2_closeview.pdf','-dpdf');